---
- name: Create a test file on all servers
  hosts: all
  become: yes
  tasks:
    - name: Ensure the file exists
      ansible.builtin.file:
        path: /tmp/ansible_test.txt
        state: touch
        mode: '0644'

